//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 12:36:58 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.domoroboto.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.domoroboto;
